### PR TITLE
Create es.kr.json

### PR DESCRIPTION
**Pull request by castigar**
Preparing Korean Translation on Escalation

### CODE REVIEW

**Comment by castigar** [comment]
Preparing Korean Translation on Escalation

**Comment by castigar** [comment]
It is confusing to merge pull requests.

**Comment by Alsciende** [comment]
I can see that you're having some troubles. I'll try to prepare the Korean translation.

**Comment by Alsciende** [comment]
Ok, the files should be ready for you to translate.

**Pull request closed without merging**
