### PR TITLE
Add newly announced cards for Martial Law data pack

### PR DESCRIPTION
**Pull request by lostie**
This introduces the newly [announced](https://www.fantasyflightgames.com/en/news/2016/8/31/martial-law/) cards for the upcoming 5th pack of the Flashpoint cycle: Martial Law.

It doesn't include **Nihongai Grid** or **Reaver** as there wasn't enough information to describe the cards.

### CODE REVIEW

**Comment by Alsciende** [comment]
Thank you Sergio!

**Comment by zaroth** [comment]
Anson Rose is missing the quotes in flavor. Other than that, looks good to me. :+1:  As for merging actual game content and not just JSON reorganization, I'm leaving it up to Alsciende :)

11084 Equivocation https://images-cdn.fantasyflightgames.com/filer_public/80/0d/800db34d-8041-4bd9-9bb7-f508f23196b4/adn40-equivocation.png
11085 Misdirection https://images-cdn.fantasyflightgames.com/filer_public/63/27/63278c89-4b66-4ba2-af7a-f28cfb786c74/adn40-misdirection.png
11087 Interdiction https://images-cdn.fantasyflightgames.com/filer_public/10/61/10616fff-a3b1-4b76-8900-6d22647dff79/adn40-interdiction.png
11096 Anson Rose https://images-cdn.fantasyflightgames.com/filer_public/c7/40/c740703f-c4a9-405c-8781-d088a54fc18b/adn40-anson-rose.png
11097 Mausolus https://images-cdn.fantasyflightgames.com/filer_public/72/9d/729dce86-3247-4f42-9710-aa4f9eac6efd/adn40-mausolus.png

**Comment by lostie** [comment]
🏆

**Comment by Alsciende** [comment]
it's online

**Pull request merged**
