### PR TITLE
add missing flavor & trash cost, zh bm pack.

### PR DESCRIPTION
**Pull request by stimzh**
Please also compile es.zh.json and "neutral" in faction.zh.json.

### CODE REVIEW

**Comment by Alsciende** [comment]
> Please also compile es.zh.json and "neutral" in faction.zh.json.

What do you mean? I've updated the zh locale. Can you tell me what is wrong?

**Comment by Alsciende** [comment]
Ok I see. For example on Scarcity of Resources, the word "Neutral" is not translated.

**Comment by stimzh** [comment]
Thank you. And yes, all corp and runner neutral cards are labeled "neutral" instead of "中立"(Chinese).

**Comment by Alsciende** [comment]
That should be fixed now.

**Pull request merged**
