### PR TITLE
Blood money

### PR DESCRIPTION
**Pull request by gereons**
add spoiled cards from Blood Money announcement

### CODE REVIEW

**Comment by JoelCFC25** [comment]
* In the text of Credit Crash you need to capitalize "corp". 
* Change "a" to "an" for the second word in Liquidation's text.

**Comment by stimhackcn** [comment]
- Decksize line in C.I. Fund is redundant.
- [Beth Kilrain-Chang](https://images-cdn.fantasyflightgames.com/filer_public/e6/7a/e67a4d3a-ba26-47a9-9fe9-069256660f32/adn36-41_cardfan_01.png) could be added as well.

**Comment by Alsciende** [comment]
I'll wait for a commit fixing those issues before merging.

**Comment by gereons** [comment]
incoming :)

**Comment by Alsciende** [comment]
Actually it's been taken care of, I think : https://github.com/zaroth/netrunner-cards-json/pull/48

**Comment by Alsciende** [comment]
Oh no, that PR was closed, not merged.

**Comment by Alsciende** [comment]
Deployed: https://netrunnerdb.com/en/set/bm/list/name

Thanks!

**Comment by Alsciende** [comment]
Typo on CI Fund? "If there on"?

**Comment by gereons** [comment]
Not sure I understand the question, "If there on" doesn't occur anywhere

**Comment by Alsciende** [comment]
Sorry. I actually totally misread it.I just didn't see the "are" in the second line :-/

**Pull request merged**
