### PR TITLE
Update kr translations

### PR DESCRIPTION
**Pull request by castigar**
fixing some typing errors.

### CODE REVIEW

**Comment by castigar** [comment]
When does the json file for translation on blood money comes up?
I'm looking forward to upload it. lol.

**Comment by gereons** [comment]
Simply start with a copy of bm.json and add it yourself.

**Comment by castigar** [comment]
hmm, idk how to copy files on github.
if i create new file and name it like 'bm.kr.json', does it work?

**Comment by Alsciende** [comment]
Yes, it works. I'll wait for you to create it, then I'll do some modifications to the repository.

**Pull request merged**
